public class IntegrationConstants {
    public static final String STATUS_PENDING = 'PENDING';
    public static final String STATUS_PROCESSING = 'PROCESSING';
    public static final String STATUS_SUCCESS = 'SUCCESS';
    public static final String STATUS_ERROR = 'ERROR';
    public static final String STATUS_UNKNOWN = 'UNKNOWN';

    public static final String RESULT_SUCCESS = 'SUCCESS';
    public static final String RESULT_ERROR = 'ERROR';
    public static final String RESULT_UNKNOWN = 'UNKNOWN';

    private IntegrationConstants() {}
}
